#! /bin/bash 
models=$(catkin locate)'/simulation/models/'
#needs to match rover names in rqt_rover_gui/src/rover_gui_plugin.cpp 
#QString rovers[8] = {"achilles", "aeneas", "ajax", "diomedes", "hector", "paris", "thor", "zeus"};
rovers=(achilles aeneas ajax diomedes hector paris thor zeus)
for rover in "${rovers[@]}"
do
	echo 'Creating' $rover
	mkdir $models$rover
	cp $models'swarmie/model.config' $models'swarmie/model.sdf' $models$rover'/'
	sed -i -e 's/{roverName}/'$rover'/g' $models$rover'/model.sdf'
	echo '<!-- Generated by buildSwarmieTemplates.sh on '`date` 'by' $USER 'on' $HOSTNAME ' -->' >>$models$rover'/model.sdf'
	sed -i -e 's/{roverName}/'$rover'/g' $models$rover'/model.config'
	echo '<!-- Generated by buildSwarmieTemplates.sh on '`date` 'by' $USER 'on' $HOSTNAME ' -->' >>$models$rover'/model.config'
done

