# A remote rover will make this request the first time it sees a corner of home,
# when it's determining which option all the rovers will use to generate the
# home to odom transform.

# The option the remote rover would like to use. The rover processing this
# request will accept this option if it's the same option that it's using
# already, or if it's option 2, which takes precedence over option 1. The rover
# processing the request will also switch options and clear any data made
# obsolete by doing so (like lists of cube coordinates in the home frame), if
# necessary.
uint8 option_num

# Rover's name, to make following a log of requests a little easier.
string rover_name
---
# Whether the rover processing the request is ok with that choice. The client
# is expected to use this response to decide if it can use it's choice, or if
# it needs to switch to what everyone else is using.
bool success