/*
 * Calibration.h
 *
 *  Created on: Jan 10, 2018
 *      Author: maximus
 */

#ifndef CALIBRATION_H_
#define CALIBRATION_H_

#include <stdint.h>

#define CAL_HEADER_WORD 0xaa995566

// Track the maximum/minimum magnetometer values for runtime calibration.
// These will be invalid as soon as the rover drives because the field
// generated by the motors. These will be stored when abridge sends a command.
struct cal_t {
  uint32_t header = CAL_HEADER_WORD;
  struct cal_data_t {
    int16_t x_min = INT16_MAX;
    int16_t x_max = INT16_MIN;
    int16_t y_min = INT16_MAX;
    int16_t y_max = INT16_MIN;
    int16_t z_min = INT16_MAX;
    int16_t z_max = INT16_MIN;
  } data;
  uint32_t crc32 = 0;
};

extern struct cal_t calibration;
extern bool stored_calibration_used;

void clearCalibration();
void clearObservedCalibration();
void commitCalibration();
bool readCalibration(struct cal_t &cal);


#endif /* CALIBRATION_H_ */
