
grid_map_visualizations:
  - name: target_map
    type: occupancy_grid
    params:
     layer: targets
     data_min: 0
     data_max: 1
  - name: surface_normals
    type: vectors
    params:
      layer_prefix: facing_
      position_layer: targets
      scale: 0.06
      line_width: 0.005
      color: 15600153 # red
      